// AUTO-GENERATED by scripts/publish-generated-articles.mjs — do not edit manually.
import type { BlogPost } from "./types";
import { post as post_land_for_sale_in_mersin_risks_and_opportunities_for_buyers } from "./posts/land-for-sale-in-mersin-risks-and-opportunities-for-buyers";

export const autoPosts: BlogPost[] = [
  post_land_for_sale_in_mersin_risks_and_opportunities_for_buyers,
];
