// AUTO-GENERATED by scripts/publish-generated-articles.mjs — do not edit manually.
import type { BlogPost } from "./types";
import { post as post_apartments_for_sale_in_mersin_what_foreign_buyers_should_compare } from "./posts/apartments-for-sale-in-mersin-what-foreign-buyers-should-compare";
import { post as post_currency_considerations_when_buying_property_in_mersin } from "./posts/currency-considerations-when-buying-property-in-mersin";
import { post as post_due_diligence_checklist_before_buying_property_in_mersin } from "./posts/due-diligence-checklist-before-buying-property-in-mersin";
import { post as post_land_for_sale_in_mersin_risks_and_opportunities_for_buyers } from "./posts/land-for-sale-in-mersin-risks-and-opportunities-for-buyers";
import { post as post_retiring_in_mersin_property_options_for_overseas_buyers } from "./posts/retiring-in-mersin-property-options-for-overseas-buyers";

export const autoPosts: BlogPost[] = [
  post_apartments_for_sale_in_mersin_what_foreign_buyers_should_compare,
  post_currency_considerations_when_buying_property_in_mersin,
  post_due_diligence_checklist_before_buying_property_in_mersin,
  post_land_for_sale_in_mersin_risks_and_opportunities_for_buyers,
  post_retiring_in_mersin_property_options_for_overseas_buyers,
];
